name: build node
on: 
  workflow_call:
   inputs:
    username:
     required: true
     type: string
   secrets:
    envPAT:
     required: true

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14.x'
        - run: npm install
        - run: npm test
